[data]                               # Options for what data to output from simulations and where to
statsOutput       = "stats.csv"      # CSV file to output stats from runs to
traceOutputPrefix = "experiment"     # Prefix of filenames to output full run traces for visualisation, each run numbered
numberRuns        = 2                # Number of simulation runs to perform
numberTraces      = 0                # Number of of those simulation runs to trace for visualisation

[run]                                # Options for the simulation model
numberTicks      = 20                # Number of simulation ticks/time steps
spaceWidth       = 100               # Spatial width of the area in which agents interact
spaceHeight      = 100               # Spatial height of the area in which agents interact
numberAgents     = 1000              # Number of agents in initial state
numberBehaviours = 20                # Number of different behaviours agents can adopt
numberObstacles  = 20                # Number of square obstacles placed in the area
obstacleSide     = 5                 # The length of each side of a square obstacle
numberExits      = 50                # The number of exit/entry points around the space
threshold        = 10.0              # Threshold distance beyond which agents do not interact
maxMove          = 1.41421           # Maximum distance an agent can move per time step