[data]
statsOutput       = "stats.csv"
traceOutputPrefix = "experiment"
numberRuns        = 1
numberTraces      = 0

[run]
numberTicks      = 10
spaceWidth       = 100
spaceHeight      = 100
numberAgents     = 1000
numberBehaviours = 20
numberObstacles  = 20
obstacleSide     = 5
numberExits      = 50
threshold        = 10.0
maxMove          = 1.41421