# For simulation without exit/entry, set numberExits = 0
# For simulation without obstacles, set numberObstacles = 0
# For simulation without movement, set maxMove = 0.0
# For simulation without distance influencing interaction chance, set distanceInfluence to "Uniform" instead of "Linear"
# For simulation without space (threshold distance) affecting network construction or anything else, set netConstruction to "Random" instead of "Distance"

[data]                               # Options for what data to output from simulations and where to
statsOutput       = "stats.csv"      # CSV file to output stats from runs to, NOTE: appends to existing content
traceOutputPrefix = "experiment"     # Prefix of filenames to output full run traces for visualisation, each run numbered
numberRuns        = 10               # Number of simulation runs to perform
numberTraces      = 0                # Number of of those simulation runs to trace for visualisation
randomSeed        = -1               # Random seed to use for 1st run, incremented for each subsequent run: use -1 for no fixed seed (time-based randomness)

[run]                                # Options for the simulation model
numberTicks       = 200              # Number of simulation ticks/time steps
spaceWidth        = 100              # Spatial width of the area in which agents interact
spaceHeight       = 100              # Spatial height of the area in which agents interact
numberAgents      = 1000             # Number of agents in initial state
numberBehaviours  = 2                # Number of different behaviours agents can adopt
numberObstacles   = 30               # Number of square obstacles placed in the area
obstacleSide      = 5                # The length of each side of a square obstacle
numberExits       = 50               # The number of exit/entry points around the space
threshold         = 10.0             # Threshold distance beyond which agents do not interact
distanceInfluence = "Linear"         # How distance influences interaction: either "Linear" for influence decreasing linearly by distance or "Uniform" for no effect of distance
netConstruction   = "Distance"       # How the network is generated: either "Distance" for by spatial distance threshold or "Random" if random network of same expected degree as geometric network
transmission      = "Air"            # Determines how interaction is blocked by obstacles: "Light" requires line of sight while "Air" does not
maxMove           = 1.5              # Maximum distance an agent can move per time step, e.g. 0.0 for no movement, 1.0 for vertical/horiztonal, 1.5 for also diagonal
